### ISSUE TITLE
F-Droid failed to build

### ISSUE THREAD

**Issue by linsui** [xbrowsersync/app#313]
```
+ npm install
+ cd res/android
+ cordova telemetry off
(node:3389) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/local/lib/node_modules/cordova/node_modules/objectorarray/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
+ cordova prepare
(node:3340) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/local/lib/node_modules/cordova/node_modules/objectorarray/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
Discovered platform "android@^8.1.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@^8.1.0
(node:3340) Warning: Accessing non-existent property 'android@^8.1.0' of module exports inside circular dependency
Error: Failed to fetch platform cordova-android@^8.1.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Could not determine package name from output:
added 85 packages, and audited 86 packages in 13s
2 packages are looking for funding
  run `npm fund` for details
3 high severity vulnerabilities
To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
No platforms added to this project. Please use `cordova platform add <platform>`.
```

The build block is

```yml
  - versionName: 1.6.0
    versionCode: 16001
    commit: v1.6.0.1227
    sudo:
      - sysctl fs.inotify.max_user_watches=524288
      - curl -Lo node.tar.xz https://nodejs.org/dist/v16.2.0/node-v16.2.0-linux-x64.tar.xz
      - echo "e134c8738761ab908aac3b62efa4865d8a7c73e40cc7758c6e99244921696216 node.tar.xz"
        | sha256sum -c -
      - tar xJf node.tar.xz
      - cp -a node-v16.2.0-linux-x64/. /usr/local/
      - npm install -g cordova@9.0.0
    output: build/cordova/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
    prebuild:
      - npm install
      - cd res/android
      - cordova telemetry off
      - cordova prepare
    scandelete:
      - res/android/platform/android/cordova
      - build/cordova/node_modules/cordova-android
    build:
      - npm run build:android
      - cd build/cordova
      - cordova build android --release
 ```

Could you please take a look? Thanks!
