### ISSUE TITLE
Bookmarks duplicated with bogus tags

### ISSUE THREAD

**Issue by cjnaz** [xBrowserSync/App#57]
### Steps to reproduce
1.  Not quite sure.  One possibility is that I had a machine off of the internet for a while, and the bookmarks seemed to be gone.  When reconnected I think I had to re-add the sync ID.  That machine is on App 1.4.0.
2.  It could be an artifact of using the 1.4.1 Beta on one machine, while others were on 1.4.0. The corruption may have happened if the 1.4.0 machine could not understand the received sync data created by the 1.4.1 machine.
3.  The corruption could possibly be related to creating a bookmark from Firefox (running 1.4.0).

### Expected behaviour
Tell us what should happen

### Actual behaviour
All bookmarks were duplicated, with the duplicates having 3 bogus tags "Doc", "Howto", and "P910nd.Server".  I may have created a new bookmark to a page with these words on it from the Firefox 1.4.0 machine.

### Client app information
**App Platform:** (Chrome, Firefox, iOS, etc) 
Chrome mostly on several machines.  Firefox on one of the machines.

**App Platform Version:** 
App 1.4.1 Beta from about Nov 5.  (mixed 1.4.1Beta and 1.4.0)

#### Other info
If the mixed App versions is the corruption/duplication culprit then please add a strong caution against running a mixed app versions on a common syncID.  I propose that you add App version info tag in the data blob (and visible in the .json backup) so that new App versions may be coded to deal with a version difference.

**Comment by nero120** [comment]
Hi @cjnaz, I doubt running those two app versions would cause that issue, the only difference was in the sync upgrade logic. Sync data does include the app version for the purposes of upgrading when required. Are you able to reproduce this? Otherwise not sure what else I can do.

**Comment by cjnaz** [comment]
I can't reproduce this.  Let's call it a sighting and we'll mark it closed.  I'm working up a python tool for editing the backup file.  If I come up with some useful edit features I'll post the tool.  First order I'll use it to strip out the duplicates.

**Comment by nero120** [comment]
Nice one @cjnaz!

**Comment by mblais** [comment]
>  I'm working up a python tool for editing the backup file. If I come up with some useful edit features I'll post the tool. First order I'll use it to strip out the duplicates.

@cjnaz Can you share that tool with us? I had to write my own hacky script to filter out duplicate bookmarks from the backup after encountering a similar situation.

**Comment by cjnaz** [comment]
I've not tried this on a recent xbs backup.  Please post and issue on my
repo if you have problems.  I still need to clean up my bookmarks, as all
in the bookmark toolbar were duplicated.
https://github.com/cjnaz/xbsjsonedit

**Comment by cjnaz** [comment]
I've updated https://github.com/cjnaz/xbsjsonedit for working with App version 1.5.0.  This version only works on Python 3 (and properly supports unicode chars in bookmarks).  
I've added a few useful modes, including printing the bookmark hierarchy and deleting duplicate folders.  Aside from cleaning up xBrowserSync remnants, this tool can be quite useful for general bookmarks maintenance/cleanup.

```
Options:
  p:  Print the bookmarks tree hierarchy

  s:  Search term entry (currently <__NONE__>)
  t:  List   bookmark search matches
  T:  Delete bookmark search matches
  g:  List   folder names search matches
  G:  Delete folder names search matches

  d:  List   duplicate URLs
  D:  Delete duplicate URLs

  f:  List   duplicate folders
  F:  Delete duplicate folders

  x:  List   tags on folders (only leaf nodes should have tags)
  X:  Delete tags on folders

  y:  List   empty folders (may arise if all children were deleted)
  Y:  Delete empty folders
  
  w:  Write out the bookmarks data to a file
  q:  Quit/exit (Do a Write first!)
```
